spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/benchmark}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/benchmark}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
